binovo_elkar_backups:
    resource: "@BinovoElkarBackupBundle/Controller/"
    type:     annotation
    prefix:   /
login_check:
    pattern:   /login_check
logout:
    pattern: /logout
binovo_elkar_tahoe:
    resource: "@BinovoElkarTahoeBundle/Controller/"
    type:     annotation