<?php
/**
 * @copyright 2012,2013 Binovo it Human Project, S.L.
 * @license http://www.opensource.org/licenses/bsd-license.php New-BSD
 */

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130218160258 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        $sql=<<<EOF
INSERT INTO Policy (description, name                                           , hourlyHours        , hourlyDaysOfMonth, hourlyDaysOfWeek, hourlyMonths, hourlyCount, dailyHours, dailyDaysOfMonth, dailyDaysOfWeek, dailyMonths, dailyCount, weeklyHours, weeklyDaysOfMonth, weeklyDaysOfWeek, weeklyMonths, weeklyCount, monthlyHours, monthlyDaysOfMonth, monthlyDaysOfWeek, monthlyMonths, monthlyCount, yearlyHours, yearlyDaysOfMonth, yearlyDaysOfWeek, yearlyMonths, yearlyCount, include, exclude, syncFirst)
            VALUES (NULL       , 'Three times a day, monday to friday'          , '11:00|14:00|17:00', NULL             , '1|2|3|4|5'     , NULL        , 3          , '11:00'   , NULL            , '1|2|3|4|5'    , NULL       , 5         , '11:00'    , NULL             , NULL            , NULL        , 0          , '11:00'     , NULL              , NULL             , NULL         , 0           , '11:00'    , NULL             , NULL            , NULL        , 0          , NULL   , NULL   , 1),
                   (NULL       , 'At 21:00, 7 days a week'                      , NULL               , NULL             , NULL            , NULL        , 0          , '21:00'   , NULL            , '1|2|3|4|5|6|7', NULL       , 7         , '21:00'    , NULL             , NULL            , NULL        , 0          , '21:00'     , NULL              , NULL             , NULL         , 0           , '21:00'    , NULL             , NULL            , NULL        , 0          , NULL   , NULL   , 1),
                   (NULL       , 'At 21:00, monday to friday, long time storage', NULL               , NULL             , NULL            , NULL        , 0          , '21:00'   , NULL            , '1|2|3|4|5'    , NULL       , 5         , '21:00'    , NULL             , 6               , NULL        , 4          , '21:00'     , 28                , NULL             , NULL         , 22          , '21:00'    , NULL             , NULL            , NULL        , 0          , NULL   , NULL   , 1)
EOF;
        $this->addSql($sql);
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
    }
}
