#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_input medium elkarbackup/dbhost        || true
db_input low elkarbackup/dbname           || true
db_input low elkarbackup/dbusername       || true
db_input low elkarbackup/dbuserpassword   || true

db_go || true
