#!/bin/bash
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge
fi

if [ "$1" = "remove" ]; then
    deluser --system elkarbackup || echo "Problem deleting user elkarbackup"
    . /usr/share/debconf/confmodule
    a2dissite elkarbackup || true
    if [ -f /etc/init.d/apache2 ]
    then
        invoke-rc.d apache2 reload || true
    fi
    db_purge
fi
