#!/bin/bash
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge
fi

if [ "$1" = "remove" ]; then
    db_get tknikabackups/backupsusername
    username="$RET"
    if test "x$username" != xwww-data
    then
        deluser --system $username
    fi
    . /usr/share/debconf/confmodule
    a2dissite tknikabackups || true
    if [ -f /etc/init.d/apache2 ]
    then
        invoke-rc.d apache2 reload
    fi
    db_purge
fi
