#!/bin/bash
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge
fi

if [ "$1" = "remove" ]; then
    CONF="elkarbackup"
    CONFSSL="elkarbackup-ssl"
    COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)
    
    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke disconf $CONF || exit $?
        apache2_invoke dissite $CONF || exit $?
	apache2_invoke dissite $CONFSSL || exit $?
    elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
        [ ! -L /etc/apache2/conf.d/$CONF.conf ] || rm /etc/apache2/conf.d/$CONF.conf
        [ ! -L /etc/apache2/sites-enabled/$CONF.conf ] || rm /etc/apache2/sites-enabled/$CONF.conf
	[ ! -L /etc/apache2/sites-enabled/$CONFSSL.conf ] || rm /etc/apache2/sites-enabled/$CONFSSL.conf
    fi

    deluser --system elkarbackup || echo "Problem deleting user elkarbackup"
    . /usr/share/debconf/confmodule

    if [ -f /etc/init.d/apache2 ]
    then
        invoke-rc.d apache2 reload || true
    fi
    db_purge
fi

update-rc.d elkarbackup-tahoe-lafs remove
